# Generated by Django 4.0.5 on 2022-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passager_informations_vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_barcode_baggage', models.CharField(max_length=10, unique=True)),
                ('passenger_and_ticket_info', models.TextField(default='information pas encore disponible')),
                ('pnr_and_baggage_info', models.TextField(default='information pas encore disponible')),
                ('baggage_weight_info', models.TextField(default='information pas encore disponible')),
                ('flight_info', models.TextField(default='information pas encore disponible')),
                ('baggage_fin_tapis', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_embarquement', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_emplacement_south', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_debarquement', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_checker_depart', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_checker_arriver', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_en_tapis_livraison', models.CharField(default='information pas encore disponible', max_length=100)),
                ('baggage_livrer', models.CharField(default='information pas encore disponible', max_length=100)),
                ('passager_depart_localisation_dgm', models.CharField(default='information pas encore disponible', max_length=100)),
                ('passager_depart_localisation_salle_attente', models.CharField(default='information pas encore disponible', max_length=100)),
                ('passager_embarquer', models.CharField(default='information pas encore disponible', max_length=100)),
                ('passager_arriver_et_recuperer_baggage', models.CharField(default='information pas encore disponible', max_length=100)),
                ('kilos_baggage_tarmaque', models.CharField(default='information pas encore disponible', max_length=100)),
                ('date_heure_operation', models.DateTimeField(auto_now_add=True)),
                ('date_operation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
