# Generated by Django 4.0.5 on 2022-06-27 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0004_alter_passager_informations_vol_agent_id_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='agent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='manifest',
            field=models.TextField(),
        ),
    ]
