# Generated by Django 4.0.5 on 2022-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0005_manifest_agent_id_alter_manifest_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='manifest',
            field=models.FileField(upload_to='files'),
        ),
    ]
