# Generated by Django 4.0.5 on 2022-06-29 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0006_alter_manifest_manifest'),
    ]

    operations = [
      
    ]
