# Generated by Django 4.0.5 on 2022-06-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0007_remove_passager_informations_vol_baggage_checker_arriver_and_more'),
    ]

    operations = [
       
    ]
