# Generated by Django 4.0.5 on 2022-06-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0008_alter_bagage_informations_vol_numero_barcode_bagage_and_more'),
    ]

    operations = [
      
    ]
