# Generated by Django 4.0.5 on 2022-06-29 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0009_alter_bagage_informations_vol_numero_barcode_bagage_and_more'),
    ]

    operations = [
      
    ]
