# Generated by Django 4.0.5 on 2022-06-29 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0010_remove_passager_informations_vol_baggage_checker_arriver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_checker_arriver',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_checker_depart',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_debarquement',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_embarquement',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_emplacement_south',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_en_tapis_livraison',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_fin_tapis',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_livrer',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='baggage_weight_info',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='kilos_baggage_tarmaque',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='numero_barcode_baggage',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='passager_arriver_et_recuperer_baggage',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='passager_depart_localisation_dgm',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='passager_depart_localisation_salle_attente',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='passager_embarquer',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='pnr_and_baggage_info',
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='bagage_weight_info',
            field=models.TextField(default='information pas encore disponible'),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='numero_barcode_passager',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_arriver_et_recuperer_baggage',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_debarquer',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_depart_localisation_dgm',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_depart_localisation_salle_attente',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_embarquer',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='pnr_and_bagage_info',
            field=models.TextField(default='information pas encore disponible'),
        ),
        migrations.CreateModel(
            name='Bagage_informations_vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_barcode_bagage', models.CharField(max_length=10, unique=True)),
                ('passenger_and_ticket_info', models.TextField(default='information pas encore disponible')),
                ('pnr_and_bagage_info', models.TextField(default='information pas encore disponible')),
                ('bagage_weight_info', models.TextField(default='information pas encore disponible')),
                ('flight_info', models.TextField(default='information pas encore disponible')),
                ('ok_bagage_fin_tapis', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_pied_avion', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_embarquement', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_emplacement_south_A', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_emplacement_south_B', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_emplacement_south_C', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_debarquement', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_checker_depart', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_checker_arriver', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_en_tapis_livraison', models.CharField(default='information pas encore disponible', max_length=100)),
                ('ok_bagage_livrer', models.CharField(default='information pas encore disponible', max_length=100)),
                ('kilos_bagage_tarmaque', models.CharField(default='information pas encore disponible', max_length=100)),
                ('date_heure_operation', models.DateTimeField(auto_now_add=True)),
                ('date_operation', models.DateField(auto_now_add=True)),
                ('agent_id_save', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
