# Generated by Django 4.0.5 on 2022-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0011_remove_passager_informations_vol_baggage_checker_arriver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_arriver',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_depart',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
    ]
