# Generated by Django 4.0.5 on 2022-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0012_passager_informations_vol_ok_passager_checker_arriver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagage_informations_vol',
            name='ok_bagage_debarquement',
        ),
        migrations.RemoveField(
            model_name='bagage_informations_vol',
            name='ok_bagage_embarquement',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_debarquer',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_depart_localisation_dgm',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_depart_localisation_salle_attente',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_embarquer',
        ),
        migrations.AddField(
            model_name='bagage_informations_vol',
            name='avion_info',
            field=models.TextField(default='information pas encore disponible'),
        ),
        migrations.AddField(
            model_name='bagage_informations_vol',
            name='ok_bagage_debarquement_arrivee',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='bagage_informations_vol',
            name='ok_bagage_debarquement_depart',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='bagage_informations_vol',
            name='ok_bagage_embarquement_depart',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='bagage_informations_vol',
            name='vol_info',
            field=models.TextField(default='information pas encore disponible'),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_debarquement_avion',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_embarquement_avion',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_dgm',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_salle_attente',
            field=models.CharField(default='information pas encore disponible', max_length=100),
        ),
    ]
