# Generated by Django 4.0.5 on 2022-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0013_remove_bagage_informations_vol_ok_bagage_debarquement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager_informations_vol',
            name='vol_info',
            field=models.TextField(default='information pas encore disponible'),
        ),
    ]
