# Generated by Django 4.0.5 on 2022-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0014_passager_informations_vol_vol_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager_informations_vol',
            name='avion_info',
            field=models.TextField(default='information pas encore disponible'),
        ),
    ]
