# Generated by Django 4.0.5 on 2022-07-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0016_remove_passager_informations_vol_vol_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagage_informations_vol',
            name='vol_info',
        ),
    ]
