# Generated by Django 4.0.5 on 2022-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0019_alter_bagage_informations_vol_avion_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='avion_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='bagage_weight_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='flight_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='kilos_bagage_tarmaque',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_checker_arriver',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_checker_depart',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_debarquement_arrivee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_debarquement_depart',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_embarquement_depart',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_emplacement_south_A',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_emplacement_south_B',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_emplacement_south_C',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_en_tapis_livraison',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_fin_tapis',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_bagage_livrer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='ok_pied_avion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='passenger_and_ticket_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='pnr_and_bagage_info',
            field=models.TextField(default=''),
        ),
    ]
