# Generated by Django 4.0.5 on 2022-07-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0020_alter_bagage_informations_vol_avion_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='avion_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='bagage_weight_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='flight_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='numero_barcode_passager',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_arriver_et_recuperer_baggage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_arriver',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_depart',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_debarquement_avion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_embarquement_avion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_dgm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_salle_attente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='passenger_and_ticket_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='pnr_and_bagage_info',
            field=models.TextField(default=''),
        ),
    ]
