# Generated by Django 4.0.5 on 2022-07-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0022_vol_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagage_informations_vol',
            name='vol_information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='vol_information',
            field=models.CharField(default='', max_length=200),
        ),
    ]
