# Generated by Django 4.0.5 on 2022-07-04 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0024_bagage_informations_vol_count_numero_barcode_bagage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='avion_info',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='bagage_weight_info',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='flight_info',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='numero_barcode_passager',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_arriver_et_recuperer_baggage',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_arriver',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_depart',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_debarquement_avion',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_embarquement_avion',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_dgm',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_salle_attente',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='passenger_and_ticket_info',
        ),
        migrations.RemoveField(
            model_name='passager_informations_vol',
            name='pnr_and_bagage_info',
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='vol_information',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Count_Bagages_Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_information', models.CharField(max_length=200, unique=True)),
                ('count_numero_barcode_bagage', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_fin_tapis', models.CharField(default='', max_length=100)),
                ('count_ok_pied_avion', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_embarquement_depart', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_emplacement_south_A', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_emplacement_south_B', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_emplacement_south_C', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_debarquement_depart', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_debarquement_arrivee', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_checker_depart', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_checker_arriver', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_en_tapis_livraison', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_livrer', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_stocke_depart', models.CharField(default='', max_length=100)),
                ('count_ok_bagage_stocke_arrivee', models.CharField(default='', max_length=100)),
                ('date_heure_operation', models.DateTimeField(auto_now_add=True)),
                ('date_operation', models.DateField(auto_now_add=True)),
                ('agent_id_save', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
