# Generated by Django 4.0.5 on 2022-07-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0025_remove_passager_informations_vol_avion_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager_informations_vol',
            name='avion_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='bagage_weight_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='flight_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='numero_barcode_passager',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_arriver_et_recuperer_baggage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_arriver',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_checker_depart',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_debarquement_avion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_embarquement_avion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_dgm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='ok_passager_localisation_salle_attente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='passenger_and_ticket_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passager_informations_vol',
            name='pnr_and_bagage_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='vol_information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Count_Passagers_Vo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_information', models.CharField(max_length=200, unique=True)),
                ('count_numero_barcode_passager', models.CharField(default='', max_length=100)),
                ('count_ok_passager_checker_depart', models.CharField(default='', max_length=100)),
                ('count_ok_passager_checker_arriver', models.CharField(default='', max_length=100)),
                ('count_ok_passager_localisation_dgm', models.CharField(default='', max_length=100)),
                ('count_ok_passager_localisation_salle_attente', models.CharField(default='', max_length=100)),
                ('count_ok_passager_embarquement_avion', models.CharField(default='', max_length=100)),
                ('count_ok_passager_debarquement_avion', models.CharField(default='', max_length=100)),
                ('count_ok_passager_arriver_et_recuperer_baggage', models.CharField(default='', max_length=100)),
                ('date_heure_operation', models.DateTimeField(auto_now_add=True)),
                ('date_operation', models.DateField(auto_now_add=True)),
                ('agent_id_save', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
