# Generated by Django 4.0.5 on 2022-07-04 10:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congoairwaysapi', '0026_passager_informations_vol_avion_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Count_Passagers_Vo',
            new_name='Count_Passagers_Vol',
        ),
    ]
