# Generated by Django 4.0.5 on 2022-07-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0027_rename_count_passagers_vo_count_passagers_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_numero_barcode_bagage',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_checker_arriver',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_checker_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_debarquement_arrivee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_debarquement_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_embarquement_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_emplacement_south_A',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_emplacement_south_B',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_emplacement_south_C',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_en_tapis_livraison',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_fin_tapis',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_livrer',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_stocke_arrivee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_bagage_stocke_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='count_ok_pied_avion',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_checker_arriver',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_checker_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_debarquement_arrivee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_debarquement_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_embarquement_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_emplacement_south_A',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_emplacement_south_B',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_emplacement_south_C',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_en_tapis_livraison',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_livrer',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_stocke_arrivee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_stocke_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_arriver_et_recuperer_baggage',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_checker_arriver',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_checker_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_debarquement_avion',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_embarquement_avion',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_localisation_dgm',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_ok_passager_localisation_salle_attente',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_numero_barcode_passager',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_arriver_et_recuperer_baggage',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_checker_arriver',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_checker_depart',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_debarquement_avion',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_embarquement_avion',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_localisation_dgm',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='passager_informations_vol',
            name='count_ok_passager_localisation_salle_attente',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
