# Generated by Django 4.0.5 on 2022-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0028_alter_bagage_informations_vol_count_numero_barcode_bagage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_numero_barcode_bagage',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_bagage_fin_tapis',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='count_ok_pied_avion',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
