# Generated by Django 4.0.5 on 2022-07-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0029_alter_count_bagages_vol_count_numero_barcode_bagage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='count_numero_barcode_passager',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
