# Generated by Django 4.0.5 on 2022-07-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0030_alter_count_passagers_vol_count_numero_barcode_passager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_bagages_vol',
            name='vol_information',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='vol_information',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
