# Generated by Django 4.0.5 on 2022-07-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0031_alter_count_bagages_vol_vol_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_passagers_vol',
            name='vol_information',
            field=models.CharField(default='', max_length=200),
        ),
    ]
