# Generated by Django 4.0.5 on 2022-07-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0032_alter_count_passagers_vol_vol_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_passagers_vol',
            name='agent_id_save',
        ),
        migrations.DeleteModel(
            name='Count_Bagages_Vol',
        ),
        migrations.DeleteModel(
            name='Count_Passagers_Vol',
        ),
    ]
