# Generated by Django 4.0.5 on 2022-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0033_remove_count_passagers_vol_agent_id_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol_information',
            name='flight_info',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
