# Generated by Django 4.0.5 on 2022-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congoairwaysapi', '0034_alter_vol_information_flight_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagage_informations_vol',
            name='numero_barcode_bagage',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
